# Generated by Django 6.0.7 on 2026-08-02 16:24

from django.db import migrations, models


def aguardando_pagamento_para_ocupada(apps, schema_editor):
    """A mesa que estava aguardando pagamento continua tendo cliente sentado,
    então o equivalente no novo conjunto de status é 'ocupada'."""
    Table = apps.get_model("tables", "Table")
    Table.objects.filter(status="aguardando_pagamento").update(status="ocupada")


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            aguardando_pagamento_para_ocupada, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('desativada', 'Desativada')], default='livre', max_length=25),
        ),
    ]
