# Generated by Django 6.0.7 on 2026-08-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addongroup',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='addonoption',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='addongroup',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addonoption',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='addonoption',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addonoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addons/'),
        ),
    ]
