# Generated by Django 6.0.7 on 2026-07-31 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado')], default='pending', max_length=15)),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('raw_webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_user_id', models.CharField(blank=True, max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='restaurants.restaurant')),
            ],
        ),
    ]
